### ISSUE TITLE
Consider use of rgrempel/elm-route-url

### ISSUE THREAD

**Issue by mccrodp** [mathieul/brunch-with-elm-bootstrap#8]
I've run into an issue with GH Page where is doesn't support SPAs. So I followed a [GH Pages SPA work around](http://www.backalleycoder.com/2016/05/13/sghpa-the-single-page-app-hack-for-github-pages/).

I integrated it into [a fork of this repo](https://github.com/ahimsayoga/brunch-with-elm-bootstrap) I'm using to initially output the free ["Business Casual" boostrap theme](https://blackrockdigital.github.io/startbootstrap-business-casual/contact.html).

If you visit http://ahimsayoga.jp/schedule now you will notice that we redirect via the [404.html](https://github.com/ahimsayoga/ahimsayoga.github.io/blob/master/404.html) in the work around and our URL is maintained, however the route is not loaded, just the homepage.

1. What does brunch do for us in this case to ensure that the correct URL is loaded
2. Is there anything we can do to ensure that URL & route / app state are in sync, or should we consider the use of [`rgrempel/elm-route-url`](https://github.com/rgrempel/elm-route-url)*

Interested in your thoughts on this, @mathieul. 

*I read about this issue via a section on a Gizra blog post: [URL change is not routing](http://www.gizra.com/content/thinking-choosing-elm/#url-change-is-not-routing).

**Comment by mathieul** [comment]
Hey @mccrodp. The GH pages SPA hack is interesting. The surprising thing is that if you view the source after going to [http://ahimsayoga.jp/schedule](http://ahimsayoga.jp/schedule) you'll notice the content of the page is not of `index.html`, but the one from `404.html`.

Using "inspect element" from the webtools does show the dynamic current page content. I noticed that the workaround javascript snippet appears after executing the Elm app. And in the workaround post it mentions: `In order to capture and restore the URL the user initially navigated to, you’ll need to add the following script tag to the head of your index.html page before any other JavaScript acts on the page’s current state`. Did you try moving `<script>require('js/initialize');</script>` after the workaround js snippet?

**Comment by mccrodp** [comment]
Thank you @mathieul!!! It seems I don't read things thoroughly. I moved the script tag to be the first element in the `head` as there is no need to load anything else if we are redirecting anyway.

Thanks a lot for that, it seems the routing package was not the problem 😄
